baseurl = "/"
title = "Fiona Paine"

theme = "hugo-coder"
#theme = "coder-portfolio"
languagecode = "en"

paginate = 20
canonifyurls = true
# Custom CSS
custom_css = []
rtl = true
#avatarurl = "" #images/fiona.jpg" # Contain the path of the optionnal avatar in the static folder
itemscentered = true
footercontent = " " # Add footer content

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[permalinks]
    posts = "posts/:title/"
    default = ":title/"

[params]
    author = "Fiona Paine"
    description = "personal website"
    keywords = " "
    info = "I'm an Assistant Professor at Texas A&M University Mays Business School. I received a Finance PhD from MIT in June of 2025. My research interests are in Corporate Finance, Entrepreneurship, Private Equity, and Venture Capital."              
    info2 = " "
    disqusShortname = " "
    pic = "images/fiona_pro.jpg" # images/fiona_plain.jpg Contain the path of the optionnal avatar in the static folder

    footercontent = " " # Add footer content

[[params.social]]
    name = ""
    weight = 1
    url = "https://fionapaine.com/Research"

[[menu.main]]
    name = "Research"
    weight = 1
    url = "/research/"
    
[[menu.main]]
    name = "CV"
    weight = 1
    url = "https://drive.google.com/file/d/11aXPG0ZTBKT_wB6XdgGflB2iMzwTC5OY/view?usp=drive_link"
    
[[menu.main]]
    name = "University Page"
    weight = 1
    url  = "https://mays.tamu.edu/directory/fiona-paine/"


