baseurl = "/"
title = "Fiona Paine"

theme = "hugo-coder"
#theme = "coder-portfolio"
languagecode = "en"

paginate = 20
canonifyurls = true
# Custom CSS
custom_css = []
rtl = true
#avatarurl = "" #images/fiona.jpg" # Contain the path of the optionnal avatar in the static folder
itemscentered = true
footercontent = " " # Add footer content

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[permalinks]
    posts = "posts/:title/"
    default = ":title/"

[params]
    author = "Fiona Paine"
    description = "Fiona Paine's personal website"
    keywords = " "
    info = "I'm a PhD student in financial economics at MIT Sloan. I will be on the 2024-2025 Job Market. My research interests are in Corporate Finance, Entrepreneurship, Private Equity, and Venture Capital."              
    info2 = " "
    jobmarketpaperurl = "https://drive.google.com/file/d/1DZ_xX92SgBKOmgTY479Ss8ns0g930bex/view?usp=drive_link"
    jobmarketpapertitle = "Not on Terra FIRRMA: Foreign Investment In US Startups and Innovation"
    jobmarketpaperabstract = " "
    disqusShortname = " "
    pic = "images/fiona_pro.jpg" # images/fiona_plain.jpg Contain the path of the optionnal avatar in the static folder

    footercontent = " " # Add footer content

#[[params.social]]
#    name = "Github"
#    weight = 1
#    url = "https://github.com/painef"

[[params.social]]
    name = "CV"
    weight = 1
    url = "https://drive.google.com/file/d/11aXPG0ZTBKT_wB6XdgGflB2iMzwTC5OY/view?usp=drive_link"

[[params.social]]
    name = "MIT Page"
    weight = 2
    url = "https://mitsloan.mit.edu/programs/phd/fiona-paine"
    
#[[menu.main]]
#    name = "About"
#    weight = 1
#    url = "/about/"
    
[[menu.main]]
    name = "Research"
    weight = 1
    url = "/research/"
    
#[[menu.main]]
#    name = "Other"
#    weight = 3
#    url  = "/Other/"


