baseurl = "/"
title = "Fiona Paine"

theme = "hugo-coder"

languagecode = "en"

paginate = 20
canonifyurls = true
# Custom CSS
custom_css = []

avatarurl = "images/fiona.jpg" # Contain the path of the optionnal avatar in the static folder

footercontent = "Enter a text here." # Add footer content

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[permalinks]
    posts = "posts/:title/"
    default = ":title/"

[params]
    author = "Fiona Paine"
    description = "Fiona Paine's personal website"
    keywords = "blog,developer,personal"
    info = "Economist and Data Scientist"
    disqusShortname = "yourdiscussshortname"
    pic = "images/fiona.jpg" # Contain the path of the optionnal avatar in the static folder

    footercontent = "Enter a text here." # Add footer content

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/painef"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/paine_f"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/fiona-paine-216a3a8a/"
    
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"

[[menu.main]]
    name = "Writing"
    weight = 2
    url  = "/Writing/"
    
[[menu.main]]
    name = "Other"
    weight = 3
    url = "/test/"



