baseurl = "/"
title = "Fiona Paine"

theme = "hugo-coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[permalinks]
    posts = "posts/:title/"
    default = ":title/"

[params]
    author = "Fiona Paine"
    description = "Fiona Paine's personal website"
    keywords = "blog,developer,personal"
    info = "Economist and Data Scientist"

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/johndoe/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/johndoe/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/fiona-paine-216a3a8a/"
    
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"

[[menu.main]]
    name = "Projects"
    weight = 2
    url  = "/posts/"
    
[[menu.main]]
    name = "Other"
    weight = 3
    url = "/test/"



