baseurl = "/"
title = "Fiona Paine"

theme = "hugo-coder"
#theme = "coder-portfolio"
languagecode = "en"

paginate = 20
canonifyurls = true
# Custom CSS
custom_css = []
rtl = true
#avatarurl = "" #images/fiona.jpg" # Contain the path of the optionnal avatar in the static folder
itemscentered = true
footercontent = " " # Add footer content

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[permalinks]
    posts = "posts/:title/"
    default = ":title/"

[params]
    author = "Fiona Paine"
    description = "Fiona Paine's personal website"
    keywords = "blog,developer,personal"
    info = "I am a PhD student in Finance at MIT Sloan."
    disqusShortname = "yourdiscussshortname"
    pic = "images/fiona_pro.jpg" # images/fiona_plain.jpg Contain the path of the optionnal avatar in the static folder

    footercontent = "" # Add footer content

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/painef"
#[[params.social]]
#    name = "SSRN"
#    weight = 2
#    url = "https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=3940444"

[[params.social]]
    name = "MIT Page"
    weight = 3
    url = "https://mitsloan.mit.edu/programs/phd/fiona-paine"
    
#[[menu.main]]
#    name = "About"
#    weight = 1
#    url = "/about/"
    
[[menu.main]]
    name = "Research"
    weight = 1
    url = "/research/"
    
#[[menu.main]]
#    name = "Other"
#    weight = 3
#    url  = "/Other/"


