---
title: "Five Country Indicators"
author: "Fiona Paine"
date: 2018-07-23
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
---

Big data has arrived….and people are drowning in it. One solution is to create a black box. A machine learning algorithm that can synthesize all the data and spit out an answer to any question. But how can non-machines (aka humans) understand and analyze the glut of numbers? The key is to look at indicators. Numbers that can serve as proxies for larger trends and concepts. GDP? An indicator of economic health. CO2 concentration in the atmosphere? An indicator of global warming and severe weather trends. There is even a new NPR podcast called “The Indicator”.  

Indicators are tricky because they give an incomplete view. Whether a person is naive or self serving, the choice of indicator will bias the conclusions drawn. So I challenged myself to come up with (and defend) 5 indicators that could give the most complete picture of a country. Of course a valid question would be: how can you justify a one size fits all approach? Surely the indicators to look at for Canada would be different than for Somalia. While Canada and Somalia are dissimilar, knowing that assumes prior knowledge. Are they different in size of economy? Violence per capita? Level of democratic institutions? This set of indicators is designed to give the prior knowledge that allows deeper, more sophisticated questions to be asked and then hopefully answered using more data.  

I freely admit that my set of indicators isn’t groundbreaking. They are mostly the main variables cited by commentators and news articles. This exercise has value not because of what it looks at, but because of what it ignores. It’s the difference between google and a librarian. Even selecting only from a set of common variables, can be overwhelming. A page could be filled with the indicators not included. My main criteria was coverage: variables must be available for all countries. 

*First, I explain my indicator choices. Then, I chose a few illustrative test cases: US, China, Brazil, Switzerland, Somalia.*

##### Indicator 1: 

##### Indicator 2: 

##### Indicator 3: 

##### Indicator 4: 

##### Indicator 5: 


```{r cars}
summary(cars)
fit <- lm(dist ~ speed, data = cars)
fit
plot(cars)
```


